### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by zhztheplayer** [Intel-bigdata/arrow#14]
Due to 
> cpp: usr/bin/ld: cannot find -lgandiva_protobuf

CMake flags used: 
`-DCMAKE_BUILD_TYPE=Debug -DARROW_GANDIVA_JAVA=ON -DARROW_GANDIVA=ON -DARROW_PARQUET=ON -DARROW_HDFS=ON -DARROW_BOOST_USE_SHARED=ON -DARROW_JNI=ON`

**Comment by zhztheplayer** [comment]
Not familiar with cmake configs but since I changed a line of `gandiva_protobuf` to `gandiva_protobuf_static` from following `add_arrow_lib` config block:
https://github.com/Intel-bigdata/arrow/blob/ed7e20e3e56cb6e08e7b6330d526edd3f2eeb23b/cpp/src/gandiva/jni/CMakeLists.txt#L88-L107
then everything works fine.

**Comment by xuechendi** [comment]
Gandiva_protobuf is a layer extracted from gandiva, @zhouyuan also said it need some header copied to system lib to make it work. Ping @zhouyuan here to see his input

**Comment by zhouyuan** [comment]
The current integration work may require some hackish compile

- libgandiva_protobuf.so should be already generated in cpp/relase-build/release even though didnt compile.

my hack is to manually copy libgandiva_protobuf.so to /usr/local/lib, then `ldconfig`, then it should compile

-  there maybe some missing headers you may need to install them manually: 

1 | /root/git/t/SparkColumnarPlugin-master/cpp/src/jni/jni_wrapper.cc:5:10:   fatal error: gandiva/jni/protobuf_utils.h: No such file or directory   #include <gandiva/jni/protobuf_utils.h>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- | --
2 | In file included from   /root/git/t/SparkColumnarPlugin-master/cpp/src/jni/jni_wrapper.cc:5:   /usr/local/include/gandiva/jni/protobuf_utils.h:19:10:   fatal error: Types.pb.h: No such file or directory   #include "Types.pb.h"               ^~~~~~~~~~~~
3 | /usr/local/include/arrow/compute/kernels/groupby_aggregate.h:24:10:   fatal error: arrow/compute/kernels/util_internal.h: No such file or directory   #include "arrow/compute/kernels/util_internal.h"               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 | In file included from   /usr/local/include/arrow/util/hashing.h:49,                      from /usr/local/include/arrow/compute/kernels/groupby_aggregate.h:26,                      from   /root/git/t/SparkColumnarPlugin-master/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc:5:   /usr/local/include/arrow/vendored/xxhash.h:24:10: fatal   error: arrow/vendored/xxhash/xxhash.h: No such file or directory   #include "arrow/vendored/xxhash/xxhash.h"               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 | In file included from   /usr/local/include/arrow/vendored/xxhash.h:24,                      from /usr/local/include/arrow/util/hashing.h:49,                      from /usr/local/include/arrow/compute/kernels/groupby_aggregate.h:26,                      from /root/git/t/SparkColumnarPlugin-master/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc:5:   /usr/local/include/arrow/vendored/xxhash/xxhash.h:532:12:   fatal error: xxhash.c: No such file or directory   #  include "xxhash.c"   /*   include xxhash function bodies as `static`, for inlining */                 ^~~~~~~~~~

**Comment by zhztheplayer** [comment]
Thanks @zhouyuan and @xuechendi for the help! It is weird that I didn't experience as much difficulties on the missing headers but everything eventually worked. I'll keep this as a memo. :)

**Comment by zhztheplayer** [comment]
Closing. One can reopen if necessary.
