### ISSUE TITLE
[ArrowDataSource Performance] Inefficiency at VectorLoader.load()

### ISSUE THREAD

**Issue by zhztheplayer** [Intel-bigdata/arrow#63]
following up to #49 

The extra bit buffer and offset buffer allocations in `root.setRowCount()` can slow the reader down by up to 15% (581ms to 720ms in my case, `select * from lineitem`, 4096 batchsize).

I am thinking if we could be able to deal with the issue #49 fixed in another way. @rongma1997 please let me know if you have any suggestions.

**Comment by rongma1997** [comment]
I see... I was wrong. 
Indeed moving ```root.setRowCount()``` to the top cause many unexpected extra memory allocations. Sorry for affecting your work and we should remove this change. I'll temporarily disable the shuffle compression and see what I can do when their Java comresssion API is ready.
Will you change it back with your recent PR? Or I can create a new one right away.

Also @zhouyuan

**Comment by zhztheplayer** [comment]
Thanks @rongma1997 ! It's not needed to apologize as we didn't focus on reader's performance until the latest development iteration. We can temporarily disable it and I think there should be some alternative solutions for #49 that are less expensive (if the community is not pushing ARROW-8762 forward as fast as we expect). We can discuss later.

**Comment by zhztheplayer** [comment]
Resolved in d2050d40b4bb5e6d6b8a3512b74ac664a0df0e0c.

**Comment by zhztheplayer** [comment]
Some details about this issue:

In the past the process of loading a `ArrowRecordBatch` is (assume length is 100):

1. Call `VectorSchemaRoot.setRowCount(100)`;
  1.1. Call `FieldVector.setRowCount(100)` on each field vector;
    1.1.1 Set valueCount = 100;
    1.1.2 Create new validityBuffer, offsetBuffer(if needed), valueBuffer, using length = 100;
2. Call `FieldVector.loadFieldBuffers(ArrowBuf[] bufs)` on each field vector;
  2.1. Release validityBuffer, offsetBuffer, valueBuffer
  2.2. validityBuffer = bufs[0], offsetBuffer = bufs[1], valueBuffer = bufs[2];
  2.3. Set valueCount = 100;
3. Call `VectorSchemaRoot.close()`;
  3.1. Release validityBuffer, offsetBuffer, valueBuffer
  3.2. Set valueCount = 0;

So the problem is every time we load a record batch, we'll create buffers in 1.1.2 and release immediately in 2.1.

A proper process flow should be: 

1. Call `FieldVector.loadFieldBuffers(ArrowBuf[] bufs)` on each field vector;
  2.1. validityBuffer = bufs[0], offsetBuffer = bufs[1], valueBuffer = bufs[2];
  2.2. Set valueCount = 100;
2. Call `VectorSchemaRoot.setRowCount(100)`;
  2.1. Call `FieldVector.setRowCount(100)` on each field vector;
    2.1.1 Set valueCount = 100;
3. Call `VectorSchemaRoot.close()`;
  3.1. Release validityBuffer, offsetBuffer, valueBuffer
  3.2. Set valueCount = 0;
